name: Auth Service CI/CD

on:
  push:
    paths:
      - 'Auth-Service/**'
  pull_request:
    paths:
      - 'Auth-Service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Create JWT key files from secrets
        run: |
          mkdir -p Auth-Service/src/main/resources/jwt
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > Auth-Service/src/main/resources/jwt/app.key
          echo "${{ secrets.JWT_PUBLIC_KEY }}" > Auth-Service/src/main/resources/jwt/app.pub
        shell: bash

      - name: Create JWT test key files
        run: |
          mkdir -p Auth-Service/src/test/resources/jwt
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > Auth-Service/src/test/resources/jwt/app.key
          echo "${{ secrets.JWT_PUBLIC_KEYY }}" > Auth-Service/src/test/resources/jwt/app.pub
        shell: bash

      - name: Build Auth Service
        run: mvn -f Auth-Service/pom.xml install -DskipTests

      - name: Run Tests
        run: mvn -f Auth-Service/pom.xml test

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('Auth-Service/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f Auth-Service/pom.xml -Dsonar.projectKey=DionNuijens_Media-Connect-AuthService

      - name: Build JAR with Maven
        run: mvn -f Auth-Service/pom.xml clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./Auth-Service
          file: ./Auth-Service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest